# Generated by Django 3.0.5 on 2020-04-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barist',
            fields=[
                ('ipn', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="barista's ipn")),
                ('name', models.CharField(max_length=20, verbose_name="barista's name")),
                ('surname', models.CharField(max_length=20, verbose_name="barista's surname")),
                ('phone', models.CharField(max_length=13, verbose_name="barista's phone number")),
                ('email', models.CharField(max_length=20, null=True, verbose_name="barista's email")),
                ('notes', models.TextField(verbose_name='notes')),
            ],
        ),
    ]
