# Generated by Django 3.0.5 on 2020-04-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='dish name')),
                ('description', models.TextField(verbose_name='dish description')),
                ('type_of_dish', models.CharField(max_length=10, verbose_name='type of dish')),
                ('margin', models.IntegerField(verbose_name='margin')),
                ('price_for_one', models.IntegerField(verbose_name='price')),
                ('notes', models.TextField(verbose_name='notes')),
            ],
        ),
    ]
