# Generated by Django 3.0.5 on 2020-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barist',
            name='notes',
            field=models.TextField(null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='notes',
            field=models.TextField(null=True, verbose_name='notes'),
        ),
    ]
