# Generated by Django 3.0.5 on 2020-04-02 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_auto_20200401_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name_of_product', models.CharField(max_length=30, verbose_name='name of product in invoice')),
                ('quantity_of_product', models.IntegerField(verbose_name='quantity of product in invoice')),
                ('all_price', models.IntegerField(blank=True, verbose_name='price for all products')),
                ('notes', models.TextField(blank=True, verbose_name='notes for invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name of product')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity of product in storage')),
                ('price_for_kg', models.IntegerField(verbose_name='price for one kg of product')),
                ('notes', models.TextField(blank=True, verbose_name='notes for product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrpou', models.CharField(max_length=30, verbose_name='edrpou of supplier')),
                ('name', models.CharField(max_length=30, verbose_name='name of supplier')),
                ('city', models.CharField(max_length=30, verbose_name='city of supplier')),
                ('street', models.CharField(max_length=30, verbose_name='street of supplier')),
                ('number_of_house', models.CharField(max_length=10, verbose_name='number of house of supplier')),
                ('phone', models.CharField(max_length=13, verbose_name='phone number of supplier')),
                ('email', models.CharField(max_length=30, verbose_name='email of supplier')),
                ('notes', models.TextField(blank=True, verbose_name='notes for supplier')),
            ],
        ),
        migrations.AlterField(
            model_name='barist',
            name='email',
            field=models.CharField(blank=True, max_length=20, verbose_name="barista's email"),
        ),
        migrations.AlterField(
            model_name='barist',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes for barista'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes for dish'),
        ),
        migrations.CreateModel(
            name='InvoiceRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_product', models.IntegerField(verbose_name='quantity of product')),
                ('sum', models.IntegerField(verbose_name='sum of one row')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Product')),
            ],
        ),
    ]
