# Generated by Django 3.0.5 on 2020-04-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(verbose_name='quantity of dishes in bill')),
                ('price', models.IntegerField(verbose_name='price in bill')),
                ('barist_name', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('barist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Barist')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_bonuses', models.IntegerField(verbose_name='quantity of bonuses on card')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Supplier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='edrpou',
            field=models.CharField(max_length=30, unique=True, verbose_name='edrpou of supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes for supplier'),
        ),
        migrations.CreateModel(
            name='DishRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_dish', models.FloatField()),
                ('price_for_all_portions', models.FloatField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Dish')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BillRows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity of dish')),
                ('price', models.IntegerField(verbose_name='price of dish')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Bill')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Dish')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cafe.Card'),
        ),
    ]
