# Generated by Django 3.0.5 on 2020-04-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_auto_20200404_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price in bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity of dishes in bill'),
        ),
    ]
