# Generated by Django 3.0.5 on 2020-04-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_auto_20200404_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Ukraine', max_length=30, verbose_name='country of supplier'),
        ),
    ]
