# Generated by Django 3.0.5 on 2020-04-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_supplier_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='name_of_product',
        ),
    ]
