# Generated by Django 3.0.5 on 2020-04-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_remove_invoice_name_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='margin',
            field=models.FloatField(default=0, verbose_name='margin'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price_for_one',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
    ]
