# Generated by Django 3.0.5 on 2020-04-21 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrows',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.Dish'),
        ),
    ]
